### PR TITLE
Unit test is added for multiple functions

### PR DESCRIPTION
**Pull request by emincanoguz11**
## Description

Tests are written for multiple functions like server/handle, server/route/base/http, server/route/base/json, server/route/base/state and core/entity/v1/data. (I write unit test without not testing functions)

## Test Policy Compliance

- [X] I have added or updated unit tests for my changes.
- [X] I have included integration tests where applicable.
- [X] All new and existing tests pass successfully.

### CODE REVIEW

**Comment by v0lkan** [comment]
Thanks for your contribution @emincanoguz11 .

I'll check it out once I merge and test other oustranding PRs.

**Comment by v0lkan** [comment]
Hey @emincanoguz11 ; we need the commits to be signed before we can merge this.

Thanks a lot.

**Comment by emincanoguz11** [comment]
I can't change the commits to be signed in this commits so that I must add new PR for this situation. @v0lkan can you close the PR please?

**Comment by v0lkan** [comment]
Closing this since there is a new PR.

**Pull request closed without merging**
