### PR TITLE
adding the keywords

### PR DESCRIPTION
**Pull request by krishnaduttPanchagnula**
closes #174

### CODE REVIEW

**Review by abhishek44sharma — APPROVED** [review]
lgtm

**Review by abhishek44sharma — COMMENTED** [review]
Please don't merge yet, I'm thinking if we should create another version of chart for next release? Or this is minor change we can overwrite existing version chart.
cc: @v0lkan

**Comment by v0lkan** [comment]
wrt merge, I’ll leave it to @abhishek44sharma .

We can wait until the next chart version is there.

**Comment by abhishek44sharma** [comment]
> wrt merge, I’ll leave it to @abhishek44sharma .
> 
> We can wait until the next chart version is there.

@krishnaduttPanchagnula these changes can be done in helm-chart version [0.21.0](https://github.com/vmware-tanzu/secrets-manager/tree/main/helm-charts/0.21.0)

**Pull request closed without merging**
