### PR TITLE
refactor: test-coverage yaml edited

### PR DESCRIPTION
**Pull request by marikann**
# #396 Edited test-coverage-badge workflows

## Description

 Added github acitons pipeline for test coverage badge.

## Changes

List the major changes you have made in bullet points:

- grpc required added

## Test Policy Compliance

- [ ] I have added or updated unit tests for my changes.
- [ ] I have included integration tests where applicable.
- [ ] All new and existing tests pass successfully.

## Code Quality

- [x] I have followed the coding standards for this project.
- [x] I have performed a self-review of my code.
- [x] My code is well-commented, particularly in areas that may be difficult 
      to understand.

## Documentation

- [x] I have made corresponding changes to the documentation (if applicable).
- [x] I have updated any relevant READMEs or wiki pages.

## Additional Comments

I tried this changes in my branch, it's work. 

Ekran görüntüsü 2024-02-25 211808
Ekran görüntüsü 2024-02-25 211518

**@v0lkan Could you give access permission github actions for read and write ?
Settings>Actions>General>Workflow permissions>Read and write permissions**

## Checklist

Before you submit this PR, please make sure:
- [x] You have read [the contributing guidelines][contributing] and 
      *especially* the [test policy][test-policy].
- [x] You have thoroughly tested your changes.
- [x] You have followed all the contributing guidelines for this project.
- [x] You understand and agree that your contributions will be publicly available 
  under the project’s license.

[contributing]: https://vsecm.com/docs/contributing/
[test-policy]: https://vsecm.com/docs/contributing/#add-tests-for-new-features

*By submitting this pull request, you confirm that my contribution is made under 
the terms of the project’s license and that you have the authority to grant 
these rights.*

---

Thank you for your contribution to [**VMware Secrets Manager**](https://vsecm.com)
🐢⚡️!

### CODE REVIEW

**Comment by v0lkan** [comment]
Taking a note to merge and test it… 

I‘ll merge the changes and see how the pipeline works.

If there’s an issue we can either revert the change, or amend a change.

**Review by v0lkan — APPROVED** [review]
Looking good.

Thanks for your contribution @marikann — since this is a pipeline we haven’t been using before, I don’t see any issue not to merge it.

If it breaks, we’ll record the reason, and fix it :)

**Comment by marikann** [comment]
It's looking good !!

**Comment by marikann** [comment]
plus;

https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions

From this article I understand that we have 2000 minutes per month.

I think you'd want to check this out.

But other vmware's repositories use github actions.

**Pull request merged**
