### PR TITLE
chore(docs): change VMware, Inc. to VMware secrets manager contributors. 

### LINKED ISSUE #487: change copyright statements to align with other VMware projects
Since there is no more VMware, Inc., the copyright shall reflect that.

I checked a few VMware open source projects and they have a pattern similar to this:

```text
// Copyright 2020-2022 the Pinniped contributors. All Rights Reserved.
// SPDX-License-Identifier: Apache-2.0
```

By that token, we shall change our copyright haeders into this:

```text
# /*
# |    Protect your secrets, protect your sensitive data.
# :    Explore VMware Secrets Manager docs at https://vsecm.com/
# </
# <>/  keep your secrets… secret
# >/
# <>/' Copyright 2023–present VMware Secrets Manager contributors.
# >/'  SPDX-License-Identifier: BSD-2-Clause
# */
```

### PR DESCRIPTION
**Pull request by huseyingulec**
I have made a very basic change for copyright statements, replaced `VMware, Inc.` with `VMware Secrets Manager contributors.` 

resolves #487

### CODE REVIEW

**Comment by v0lkan** [comment]
@huseyingulec: There are a lot of formatting changes. 

I’m not against them; however, we need to make this repeatable if we do a blanket formatting change.

Are you using some linter?

Can this be automated?

Can it have other styling options?

**Comment by huseyingulec** [comment]
I see, my Prettier extension is changed everything :( . It should be fine with new commits.

**Review by v0lkan — APPROVED** [review]
🌮 .

**Comment by v0lkan** [comment]
Landed!

Thanks @huseyingulec.

**Pull request merged**
